create table user_details(user_id int  generated by default as identity(start with 10 increment by 1 ) primary key,
                          name varchar2(30) not null,
                          email_id varchar2(100) unique not null,
                          password varchar2(15) not null,
                          address varchar2(50),
                          mobile_number number);
select*from user_details;
desc user_details;

drop table user_details;

alter table user_details add walllet int default '50000';
alter table user_details add Role varchar2(20) default 'user';
insert into user_details (name,email_id,password,address,mobile_number,role) values ('Premalatha','prem@gmail.com','jeev0702','Madurai',6380869312,'Admin');



create table inventory(flower_id int generated by default as identity(start with 10 increment by 1),
flower_name varchar2(50),
flower_description varchar2(100),
color varchar2(50),
retail_price number,
category_name varchar2(50),
constraint pk_flowerid primary key(flower_id));
select*from inventory;
insert into inventory(flower_name,flower_description,color,retail_price,category_name) values('mixed roses bouquet','wrapped in pink cellophane,tied withpink rippon','mixed color flowers',
                                                                                              1100,'mixed flowers'); 
insert into inventory(flower_name,flower_description,color,retail_price,category_name) values('pink carnivel','20 pink flowers,wrapped in pink paper,tied with rippon','pink color flowers',
                                                                                              726,'carnations');
insert into inventory(flower_name,flower_description,color,retail_price,category_name) values('blue orchids bunch','6 blue orchids and green leaves asserted','blue color flowers',899,'orchids');

insert into inventory(flower_name,flower_description,color,retail_price,category_name) values('colorful gerberas bunch','Bunch of 20 Mix Gerberas,Cellophane wrapping With Ribbon Bow Tied',
                                                                                              'mixed color flowers',894,'gerberas');
insert into inventory(flower_name,flower_description,color,retail_price,category_name) values('vase of red love',' 2 Red Rose,Glass Vase','red color flowers',895,'Roses');                                                                                           
 
 
alter table inventory add rating number default 0;
alter table inventory add picture varchar2(2000);

desc inventory;                                                                                           
 select*from inventory;                                                                                             
                                                                                              


create table cart_items(cart_id int generated by default as identity (start with 100 increment by 1),
                        flower_id int,
                        user_id int,
                        order_quantity int not null,
                        total_price number(10,2),
                        foreign key(user_id) references user_details(user_id),
                        foreign key(flower_id) references inventory(flower_id),
                        constraint pk_cartid primary key(cart_id));
                        
alter table cart_items add order_date date;                        

insert into cart_items(flower_id,user_id,order_quantity,total_price) values(11,11,1,726);
delete from cart_items where cart_id=106;
select*from cart_items;

create table help_support (phone_number number(15),Email varchar2(100));
insert into help_support values(6380869312,'prema@gmail.com');                       
                        
drop table cart_items cascade constraints;                        
                       

                 
                        

commit;








